### ISSUE TITLE
Make lists scrollable

### ISSUE THREAD

**Issue by liliidu** [Seymourr/meeting-planner#15]
Make lists scrollable. Overflow are at the moment hidden. 
![ss 2016-04-17 at 02 52 24](https://cloud.githubusercontent.com/assets/7442258/14584468/9c9f85b0-0447-11e6-88f3-6a3b028fd89b.png)

**Comment by augustjanse** [comment]
Funkar det inte med drag and drop eller hur var det?

**Comment by liliidu** [comment]
Yes, activityItem hamnar bakom listan.

**Comment by liliidu** [comment]
Tror att vi får låta allting overflowa i x-led och låta hela sidan scrollas ner om vi inte får till det/det blir för bökigt.

**Comment by augustjanse** [comment]
.dayview-info/#parkedActivityHeader och .test-cell måste summera till max 100%, i nuläget är det mer vilket gör att det blir overflow: hidden. Annars borde skrollen funka.

**Comment by Seymourr** [comment]
Vi gav upp på detta. Tas bort?

**Comment by augustjanse** [comment]
Lämna den uppe en stund, kan ta en snabb kik!

**Comment by augustjanse** [comment]
Tror att @Lizumi löste detta
