### ISSUE TITLE
Fix code duplication in day view/parked activities controllers

### ISSUE THREAD

**Issue by augustjanse** [Seymourr/meeting-planner#19]
Possibly by merging them.

**Comment by Seymourr** [comment]
Klart?

**Comment by dklindstrom** [comment]
Yes! Ingen duplicerad kod, men rätt ensamt i parkedActivityCtrl just nu.. Om ni tycker det ser bra ut ändå så tar jag och stänger denna, och annars kom gärna med input.

**Comment by augustjanse** [comment]
Stänger denna eftersom ingen hade några synpunkter. Nice!
