### ISSUE TITLE
Add quotes to the page

### ISSUE THREAD

**Issue by augustjanse** [Seymourr/meeting-planner#5]
To fulfill the following requirement:
- use some external data through REST API (in case you are working on proposed ideas, you will have to extend the ideas to support this)

As I understand it, we plan to add quotes somewhere to the page. This could be done fairly easily by using an API like [this one](http://quotesondesign.com/api-v4-0/) with a resource URL something like this:

`http://quotesondesign.com/wp-json/posts?filter[orderby]=rand`

We should consider somehow filtering quotes related to meetings, or something.

**Note**: If we end up choosing not to to this, write that in a comment and close the issue.

**Comment by Seymourr** [comment]
The quote would be nice to have in the createactivity view, namely beneath the title.
